# Generated by Django 4.2.11 on 2024-05-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_features_delete_apimodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='features',
            name='education',
            field=models.CharField(choices=[('primary', 'primary'), ('secondary', 'secondary'), ('tertiary', 'tertiary')], default=('primary', 'primary'), max_length=80),
        ),
        migrations.AlterField(
            model_name='features',
            name='housing',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default=('yes', 'yes'), max_length=30),
        ),
        migrations.AlterField(
            model_name='features',
            name='job',
            field=models.CharField(choices=[('admin.', 'admin.'), ('technician', 'technician'), ('services', 'services'), ('management', 'management'), ('retired', 'retired'), ('blue-collar', 'blue-collar'), ('unemployed', 'unemployed'), ('entrepreneur', 'entrepreneur'), ('housemaid', 'housemaid'), ('unknown', 'unknown'), ('self-employed', 'self-employed'), ('student', 'student')], default=('admin.', 'admin.'), max_length=80),
        ),
        migrations.AlterField(
            model_name='features',
            name='loan',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default=('yes', 'yes'), max_length=30),
        ),
        migrations.AlterField(
            model_name='features',
            name='marital',
            field=models.CharField(choices=[('married', 'married'), ('single', 'single'), ('divorced', 'divorced')], default=('married', 'married'), max_length=30),
        ),
        migrations.AlterField(
            model_name='features',
            name='month',
            field=models.CharField(choices=[('sep', 'sep.'), ('oct', 'oct'), ('nov', 'nov'), ('dec', 'dec'), ('jan', 'jan'), ('fev', 'fev'), ('mar', 'mar'), ('apr', 'apr'), ('may', 'may'), ('jun', 'jun'), ('jul', 'jul'), ('aug', 'aug')], default=('sep', 'sep.'), max_length=90),
        ),
    ]
