# Generated by Django 4.2.11 on 2024-06-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_loginactivity_delete_logentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginactivity',
            name='action',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='loginactivity',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
